//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangThuePhong
    {
        public int ID { get; set; }
        public string IDPhong { get; set; }
        public string IDNhanVien { get; set; }
        public string IDKhachHang { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<int> TienDatCoc { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual SuDungDichVu SuDungDichVu { get; set; }
    }
}
