//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.BangThuePhongs = new HashSet<BangThuePhong>();
        }
    
        public string ID { get; set; }
        public string Ten { get; set; }
        public int IDLoai { get; set; }
        public int IDTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangThuePhong> BangThuePhongs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual TrangThai TrangThai { get; set; }
    }
}
