/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `HotelManager.LoaiPhong`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `LoaiPhong`;
CREATE TABLE `LoaiPhong` (
    `Gia` LONGTEXT,
    `Id` LONGTEXT,
    `SoGiuong` LONGTEXT,
    `Ten` LONGTEXT,
    `TienPhuThu` LONGTEXT,
    `_id` VARBINARY(12) NOT NULL,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `LoaiPhong` (`Gia`, `Id`, `SoGiuong`, `Ten`, `TienPhuThu`, `_id`)
    VALUES
        ('50000', '1', '1', 'Phòng đơn thường', '30000', x'5BE9F4A2F3A066A50E16F9BA');
INSERT INTO `LoaiPhong` (`Gia`, `Id`, `SoGiuong`, `Ten`, `TienPhuThu`, `_id`)
    VALUES
        ('80000', '2', '2', 'Phòng đôi thường', '45000', x'5BE9F4F9F3A066A50E16F9BB');
INSERT INTO `LoaiPhong` (`Gia`, `Id`, `SoGiuong`, `Ten`, `TienPhuThu`, `_id`)
    VALUES
        ('110000', '3', '1', 'Phòng đơn vip 2', '50000', x'5BF1F59DA426B745F9333971');
