/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `HotelManager.DichVu`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `DichVu`;
CREATE TABLE `DichVu` (
    `Gia` LONGTEXT,
    `Id` LONGTEXT,
    `Ten` LONGTEXT,
    `_id` VARBINARY(12) NOT NULL,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `DichVu` (`Gia`, `Id`, `Ten`, `_id`)
    VALUES
        ('10000', '2', 'Sting', x'5BEA0565F3A066A50E16F9C1');
INSERT INTO `DichVu` (`Gia`, `Id`, `Ten`, `_id`)
    VALUES
        ('15000', '3', 'Bò húc', x'5BEA057CF3A066A50E16F9C2');
INSERT INTO `DichVu` (`Gia`, `Id`, `Ten`, `_id`)
    VALUES
        ('20000', '4', 'Giặt ủi', x'5BEB131BF3A066A50E16F9CD');
INSERT INTO `DichVu` (`Gia`, `Id`, `Ten`, `_id`)
    VALUES
        ('50000', '5', 'Snack', x'5BEB1D73E4E0954F6B33EA3F');
INSERT INTO `DichVu` (`Gia`, `Id`, `Ten`, `_id`)
    VALUES
        ('12000', '1', 'Coca', x'5BF24D6EA426B745F933466D');
