/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `HotelManager.KhachHang`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `KhachHang`;
CREATE TABLE `KhachHang` (
    `Cmnd` LONGTEXT,
    `Email` LONGTEXT,
    `GioiTinh` LONGTEXT,
    `Id` LONGTEXT,
    `NgaySinh` DATETIME,
    `QuocTich` LONGTEXT,
    `Sdt` LONGTEXT,
    `Ten` LONGTEXT,
    `_id` VARBINARY(12) NOT NULL,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `KhachHang` (`Cmnd`, `Email`, `GioiTinh`, `Id`, `NgaySinh`, `QuocTich`, `Sdt`, `Ten`, `_id`)
    VALUES
        ('291167733', 'nampro123@gmail.com', 'Nam', 'KH1', '1998-05-22 00:00:00.000000', 'Việt Nam', '0873712812', 'Phạm Khoa Nam', x'5BEA0B32F3A066A50E16F9CB');
INSERT INTO `KhachHang` (`Cmnd`, `Email`, `GioiTinh`, `Id`, `NgaySinh`, `QuocTich`, `Sdt`, `Ten`, `_id`)
    VALUES
        ('291867733', 'giaovu456@gmail.com', 'Nam', 'KH2', '1998-01-10 00:00:00.000000', 'Việt Nam', '0872912812', 'Nguyễn Ngọc Vũ Giao', x'5BEA0B54F3A066A50E16F9CC');
INSERT INTO `KhachHang` (`Cmnd`, `Email`, `GioiTinh`, `Id`, `NgaySinh`, `QuocTich`, `Sdt`, `Ten`, `_id`)
    VALUES
        ('265578376', 'abcdef@gmail.com', 'Nam', 'KH3', '1997-12-27 00:00:00.000000', 'Việt Nam', '0987365266', 'Nguyễn Trọng Phú', x'5BF05ECCE0085178819A3FBD');
