/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `HotelManager.Phong`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `Phong`;
CREATE TABLE `Phong` (
    `Id` LONGTEXT,
    `LoaiPhong` VARBINARY(12),
    `Ten` LONGTEXT,
    `TrangThai` LONGTEXT,
    `_id` VARBINARY(12) NOT NULL,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DT101', x'5BE9F4A2F3A066A50E16F9BA', '101', 'Đã đặt', x'5BE9F876F3A066A50E16F9BC');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DT102', x'5BE9F4A2F3A066A50E16F9BA', '102', 'Chưa đặt', x'5BEA0444F3A066A50E16F9BD');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DT103', x'5BE9F4A2F3A066A50E16F9BA', '103', 'Chưa đặt', x'5BEA0456F3A066A50E16F9BE');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DV201', x'5BF1F59DA426B745F9333971', '201', 'Đã đặt', x'5BEA0483F3A066A50E16F9BF');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DT104', x'5BE9F4A2F3A066A50E16F9BA', '104', 'Chưa đặt', x'5BFAEAA46A22918C93572167');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DDT105', x'5BE9F4F9F3A066A50E16F9BB', '105', 'Chưa đặt', x'5BFAEAC96A22918C9357218D');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DDT106', x'5BE9F4F9F3A066A50E16F9BB', '106', 'Chưa đặt', x'5BFAEAE26A22918C935721B5');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DDT107', x'5BE9F4F9F3A066A50E16F9BB', '107', 'Chưa đặt', x'5BFAEB056A22918C935721E5');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DV202', x'5BF1F59DA426B745F9333971', '202', 'Chưa đặt', x'5BFAEB336A22918C93572219');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DV203', x'5BF1F59DA426B745F9333971', '203', 'Chưa đặt', x'5BFAEB656A22918C93572284');
INSERT INTO `Phong` (`Id`, `LoaiPhong`, `Ten`, `TrangThai`, `_id`)
    VALUES
        ('DV204', x'5BF1F59DA426B745F9333971', '204', 'Chưa đặt', x'5BFAEB7A6A22918C935722BA');
