/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `HotelManager.ChucDanh`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `ChucDanh`;
CREATE TABLE `ChucDanh` (
    `primary_key` BIGINT NOT NULL AUTO_INCREMENT,
    `Id` LONGTEXT,
    `TenChucDanh` LONGTEXT,
    `_id` VARBINARY(12),
    PRIMARY KEY (`primary_key`)
) CHARSET=utf8;

INSERT INTO `ChucDanh` (`Id`, `TenChucDanh`, `_id`)
    VALUES
        ('1', 'Giám đốc', x'5BE9E781F3A066A50E16F9B1');
INSERT INTO `ChucDanh` (`Id`, `TenChucDanh`, `_id`)
    VALUES
        ('2', 'Quản lý', x'5BE9E782F3A066A50E16F9B2');
INSERT INTO `ChucDanh` (`Id`, `TenChucDanh`, `_id`)
    VALUES
        ('3', 'Lễ tân', x'5BFAE8AE6A22918C93572094');
