/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `HotelManager.BangThuePhong`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `BangThuePhong`;
CREATE TABLE `BangThuePhong` (
    `CheckIn` DATETIME,
    `CheckOut` DATETIME,
    `Id` LONGTEXT,
    `IdKhachHang` LONGTEXT,
    `IdNhanVien` LONGTEXT,
    `IdPhong` LONGTEXT,
    `IdTenPhong` LONGTEXT,
    `TienDatCoc` LONGTEXT,
    `TrangThai` LONGTEXT,
    `_id` VARBINARY(12) NOT NULL,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `BangThuePhong` (`CheckIn`, `CheckOut`, `Id`, `IdKhachHang`, `IdNhanVien`, `IdPhong`, `IdTenPhong`, `TienDatCoc`, `TrangThai`, `_id`)
    VALUES
        ('2017-12-26 00:00:00.000000', '2017-12-28 00:00:00.000000', '1', 'KH3', 'NV1', NULL, 'DV201', '200000', 'Chưa thanh toán', x'5BFB190B6A22918C93572963');
INSERT INTO `BangThuePhong` (`CheckIn`, `CheckOut`, `Id`, `IdKhachHang`, `IdNhanVien`, `IdPhong`, `IdTenPhong`, `TienDatCoc`, `TrangThai`, `_id`)
    VALUES
        ('2017-12-26 00:00:00.000000', '2017-12-28 00:00:00.000000', '', 'KH2', 'NV1', 'DT101', NULL, '100000', 'Chưa thanh toán', x'5BFB1BE46A22918C93572A7F');
