/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `HotelManager.Users`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `Users`;
CREATE TABLE `Users` (
    `ChucDanh` LONGTEXT,
    `IdNhanVien` LONGTEXT,
    `Password` LONGTEXT,
    `_id` VARBINARY(12) NOT NULL,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `Users` (`ChucDanh`, `IdNhanVien`, `Password`, `_id`)
    VALUES
        ('Giám đốc', 'NV1', '123', x'5BE9EC9FF3A066A50E16F9B5');
INSERT INTO `Users` (`ChucDanh`, `IdNhanVien`, `Password`, `_id`)
    VALUES
        ('Quản lý', 'NV2', '456', x'5BE9F385F3A066A50E16F9B6');
